// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package organisms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// import (
//
//	"github.com/niiniyare/ruun/pkg/schema"
//	"github.com/niiniyare/ruun/views/components/atoms"
//	"github.com/niiniyare/ruun/views/components/molecules"
//
// )
//
// // Example usage templates demonstrating different form configurations
//
// // ExampleBasicForm shows a simple contact form
//
//	templ ExampleBasicForm() {
//		@EnhancedForm(EnhancedFormProps{
//			ID:          "contact-form",
//			Title:       "Contact Us",
//			Description: "Send us a message and we'll get back to you.",
//			SubmitURL:   "/api/contact",
//			ValidationURL: "/api/validate",
//			ValidationStrategy: "realtime",
//			Layout:      FormLayoutVertical,
//			Size:        FormSizeMD,
//			ShowSaveState: true,
//			Fields: []molecules.FormFieldProps{
//				{
//					ID:          "name",
//					Name:        "name",
//					Label:       "Full Name",
//					Type:        "text",
//					Required:    true,
//					Placeholder: "Enter your full name",
//					AlpineModel: "formData.name",
//					AlpineChange: "updateField('name', $event.target.value)",
//				},
//				{
//					ID:          "email",
//					Name:        "email",
//					Label:       "Email Address",
//					Type:        "email",
//					Required:    true,
//					Placeholder: "your.email@example.com",
//					AlpineModel: "formData.email",
//					AlpineChange: "updateField('email', $event.target.value)",
//				},
//				{
//					ID:          "subject",
//					Name:        "subject",
//					Label:       "Subject",
//					Type:        "select",
//					Required:    true,
//					Options: []molecules.SelectOption{
//						{Value: "general", Label: "General Inquiry"},
//						{Value: "support", Label: "Technical Support"},
//						{Value: "sales", Label: "Sales Question"},
//						{Value: "bug", Label: "Bug Report"},
//					},
//					AlpineModel: "formData.subject",
//					AlpineChange: "updateField('subject', $event.target.value)",
//				},
//				{
//					ID:          "message",
//					Name:        "message",
//					Label:       "Message",
//					Type:        "textarea",
//					Required:    true,
//					Placeholder: "Tell us about your inquiry...",
//					Rows:        5,
//					MinLength:   10,
//					MaxLength:   1000,
//					AlpineModel: "formData.message",
//					AlpineChange: "updateField('message', $event.target.value)",
//				},
//			},
//			Actions: []EnhancedFormAction{
//				{
//					ID:       "cancel",
//					Type:     "cancel",
//					Text:     "Cancel",
//					Variant:  atoms.ButtonOutline,
//					Position: "left",
//				},
//				{
//					ID:       "submit",
//					Type:     "submit",
//					Text:     "Send Message",
//					Variant:  atoms.ButtonPrimary,
//					Position: "right",
//					ValidateBefore: true,
//				},
//			},
//			InitialData: map[string]any{
//				"name":    "",
//				"email":   "",
//				"subject": "",
//				"message": "",
//			},
//			OnSubmit: "console.log('Form submitted:', formData)",
//			OnValidate: "console.log('Field validated:', $event.detail)",
//		})
//	}
//
// // ExampleMultiStepForm demonstrates a wizard-style form
//
//	templ ExampleMultiStepForm() {
//		@EnhancedForm(EnhancedFormProps{
//			ID:          "user-registration",
//			Title:       "Create Your Account",
//			Description: "Join our platform in just a few easy steps.",
//			SubmitURL:   "/api/users/register",
//			ValidationURL: "/api/users/validate",
//			AutoSaveURL: "/api/users/draft",
//			ValidationStrategy: "onblur",
//			Layout:      FormLayoutVertical,
//			ShowProgress: true,
//			ShowSaveState: true,
//			AutoSave:    true,
//			AutoSaveInterval: 30,
//			Sections: []EnhancedFormSection{
//				{
//					ID:          "personal-info",
//					Name:        "personal",
//					Title:       "Personal Information",
//					Description: "Tell us about yourself",
//					Icon:        "user",
//					Fields: []molecules.FormFieldProps{
//						{
//							ID:       "firstName",
//							Name:     "firstName",
//							Label:    "First Name",
//							Type:     "text",
//							Required: true,
//							AlpineModel: "formData.firstName",
//						},
//						{
//							ID:       "lastName",
//							Name:     "lastName",
//							Label:    "Last Name",
//							Type:     "text",
//							Required: true,
//							AlpineModel: "formData.lastName",
//						},
//						{
//							ID:       "dateOfBirth",
//							Name:     "dateOfBirth",
//							Label:    "Date of Birth",
//							Type:     "date",
//							Required: true,
//							AlpineModel: "formData.dateOfBirth",
//						},
//						{
//							ID:      "gender",
//							Name:    "gender",
//							Label:   "Gender",
//							Type:    "radio",
//							Options: []molecules.SelectOption{
//								{Value: "male", Label: "Male"},
//								{Value: "female", Label: "Female"},
//								{Value: "other", Label: "Other"},
//								{Value: "prefer-not-to-say", Label: "Prefer not to say"},
//							},
//							AlpineModel: "formData.gender",
//						},
//					},
//				},
//				{
//					ID:          "account-details",
//					Name:        "account",
//					Title:       "Account Details",
//					Description: "Set up your login credentials",
//					Icon:        "key",
//					Fields: []molecules.FormFieldProps{
//						{
//							ID:          "username",
//							Name:        "username",
//							Label:       "Username",
//							Type:        "text",
//							Required:    true,
//							MinLength:   3,
//							MaxLength:   20,
//							Pattern:     "^[a-zA-Z0-9_-]+$",
//							Placeholder: "Choose a unique username",
//							HelpText:    "Username must be 3-20 characters and contain only letters, numbers, underscores, and dashes",
//							AlpineModel: "formData.username",
//							HXPost:     "/api/users/check-username",
//							HXTrigger:  "change delay:500ms",
//							HXTarget:   "#username-feedback",
//						},
//						{
//							ID:          "email",
//							Name:        "email",
//							Label:       "Email Address",
//							Type:        "email",
//							Required:    true,
//							Placeholder: "your.email@example.com",
//							AlpineModel: "formData.email",
//							HXPost:     "/api/users/check-email",
//							HXTrigger:  "change delay:500ms",
//							HXTarget:   "#email-feedback",
//						},
//						{
//							ID:          "password",
//							Name:        "password",
//							Label:       "Password",
//							Type:        "password",
//							Required:    true,
//							MinLength:   8,
//							Pattern:     "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]",
//							HelpText:    "Password must be at least 8 characters with uppercase, lowercase, number, and special character",
//							AlpineModel: "formData.password",
//							AlpineChange: "validatePasswordStrength()",
//						},
//						{
//							ID:          "confirmPassword",
//							Name:        "confirmPassword",
//							Label:       "Confirm Password",
//							Type:        "password",
//							Required:    true,
//							AlpineModel: "formData.confirmPassword",
//							AlpineBlur:  "validatePasswordMatch()",
//						},
//					},
//				},
//				{
//					ID:          "preferences",
//					Name:        "preferences",
//					Title:       "Preferences",
//					Description: "Customize your experience",
//					Icon:        "settings",
//					Fields: []molecules.FormFieldProps{
//						{
//							ID:      "notifications",
//							Name:    "notifications",
//							Label:   "Email Notifications",
//							Type:    "checkbox-group",
//							Options: []molecules.SelectOption{
//								{Value: "newsletter", Label: "Weekly Newsletter"},
//								{Value: "updates", Label: "Product Updates"},
//								{Value: "security", Label: "Security Alerts"},
//								{Value: "marketing", Label: "Marketing Communications"},
//							},
//							AlpineModel: "formData.notifications",
//						},
//						{
//							ID:      "theme",
//							Name:    "theme",
//							Label:   "Preferred Theme",
//							Type:    "select",
//							Options: []molecules.SelectOption{
//								{Value: "light", Label: "Light Theme"},
//								{Value: "dark", Label: "Dark Theme"},
//								{Value: "auto", Label: "Auto (System)"},
//							},
//							Value:       "auto",
//							AlpineModel: "formData.theme",
//						},
//						{
//							ID:          "bio",
//							Name:        "bio",
//							Label:       "Bio",
//							Type:        "textarea",
//							Placeholder: "Tell us a bit about yourself...",
//							Rows:        4,
//							MaxLength:   500,
//							CharacterCount: true,
//							AlpineModel: "formData.bio",
//						},
//					},
//				},
//			},
//			Actions: []EnhancedFormAction{
//				{
//					ID:       "prev",
//					Type:     "button",
//					Text:     "Previous",
//					Variant:  atoms.ButtonOutline,
//					Position: "left",
//					OnClick:  "prevStep()",
//					Condition: "currentStep > 1",
//				},
//				{
//					ID:       "next",
//					Type:     "button",
//					Text:     "Next",
//					Variant:  atoms.ButtonPrimary,
//					Position: "right",
//					OnClick:  "nextStep()",
//					Condition: "currentStep < totalSteps",
//					ValidateBefore: true,
//				},
//				{
//					ID:       "submit",
//					Type:     "submit",
//					Text:     "Create Account",
//					Variant:  atoms.ButtonPrimary,
//					Position: "right",
//					Condition: "currentStep === totalSteps",
//					ValidateBefore: true,
//				},
//			},
//			InitialData: map[string]any{
//				"firstName":       "",
//				"lastName":        "",
//				"dateOfBirth":     "",
//				"gender":          "",
//				"username":        "",
//				"email":           "",
//				"password":        "",
//				"confirmPassword": "",
//				"notifications":   []string{},
//				"theme":           "auto",
//				"bio":             "",
//			},
//		})
//	}
//
// // ExampleGridForm demonstrates grid layout with conditional fields
//
//	templ ExampleGridForm() {
//		@EnhancedForm(EnhancedFormProps{
//			ID:          "product-form",
//			Title:       "Product Information",
//			Description: "Add or edit product details",
//			SubmitURL:   "/api/products",
//			ValidationStrategy: "realtime",
//			Layout:      FormLayoutGrid,
//			GridCols:    2,
//			Size:        FormSizeLG,
//			ShowSaveState: true,
//			AutoSave:    true,
//			Fields: []molecules.FormFieldProps{
//				{
//					ID:          "name",
//					Name:        "name",
//					Label:       "Product Name",
//					Type:        "text",
//					Required:    true,
//					FullWidth:   true,
//					AlpineModel: "formData.name",
//				},
//				{
//					ID:       "sku",
//					Name:     "sku",
//					Label:    "SKU",
//					Type:     "text",
//					Required: true,
//					Pattern:  "^[A-Z0-9-]+$",
//					AlpineModel: "formData.sku",
//				},
//				{
//					ID:      "category",
//					Name:    "category",
//					Label:   "Category",
//					Type:    "select",
//					Required: true,
//					Options: []molecules.SelectOption{
//						{Value: "electronics", Label: "Electronics"},
//						{Value: "clothing", Label: "Clothing"},
//						{Value: "books", Label: "Books"},
//						{Value: "home", Label: "Home & Garden"},
//					},
//					AlpineModel: "formData.category",
//					AlpineChange: "updateField('category', $event.target.value); updateSubcategories()",
//				},
//				{
//					ID:      "subcategory",
//					Name:    "subcategory",
//					Label:   "Subcategory",
//					Type:    "select",
//					Condition: "formData.category !== ''",
//					AlpineModel: "formData.subcategory",
//					HXGet:   "/api/categories/subcategories",
//					HXTrigger: "categoryChange",
//				},
//				{
//					ID:       "price",
//					Name:     "price",
//					Label:    "Price",
//					Type:     "number",
//					Required: true,
//					Min:      "0.01",
//					Step:     "0.01",
//					Prefix:   "$",
//					AlpineModel: "formData.price",
//				},
//				{
//					ID:      "salePrice",
//					Name:    "salePrice",
//					Label:   "Sale Price",
//					Type:    "number",
//					Min:     "0.01",
//					Step:    "0.01",
//					Prefix:  "$",
//					Condition: "formData.onSale",
//					AlpineModel: "formData.salePrice",
//				},
//				{
//					ID:       "stock",
//					Name:     "stock",
//					Label:    "Stock Quantity",
//					Type:     "number",
//					Required: true,
//					Min:      "0",
//					AlpineModel: "formData.stock",
//				},
//				{
//					ID:      "weight",
//					Name:    "weight",
//					Label:   "Weight",
//					Type:    "number",
//					Min:     "0",
//					Step:    "0.1",
//					Suffix:  "kg",
//					AlpineModel: "formData.weight",
//				},
//				{
//					ID:          "description",
//					Name:        "description",
//					Label:       "Description",
//					Type:        "textarea",
//					Required:    true,
//					FullWidth:   true,
//					Rows:        4,
//					MaxLength:   2000,
//					CharacterCount: true,
//					AlpineModel: "formData.description",
//				},
//				{
//					ID:      "tags",
//					Name:    "tags",
//					Label:   "Tags",
//					Type:    "tags",
//					FullWidth: true,
//					TagsEditable: true,
//					MaxTags:  10,
//					AlpineModel: "formData.tags",
//				},
//				{
//					ID:      "features",
//					Name:    "features",
//					Label:   "Features",
//					Type:    "checkbox-group",
//					FullWidth: true,
//					Columns: 2,
//					Options: []molecules.SelectOption{
//						{Value: "waterproof", Label: "Waterproof"},
//						{Value: "wireless", Label: "Wireless"},
//						{Value: "rechargeable", Label: "Rechargeable"},
//						{Value: "portable", Label: "Portable"},
//						{Value: "eco-friendly", Label: "Eco-Friendly"},
//						{Value: "premium", Label: "Premium Quality"},
//					},
//					AlpineModel: "formData.features",
//				},
//				{
//					ID:      "status",
//					Name:    "status",
//					Label:   "Status",
//					Type:    "radio",
//					Required: true,
//					Options: []molecules.SelectOption{
//						{Value: "draft", Label: "Draft"},
//						{Value: "active", Label: "Active"},
//						{Value: "inactive", Label: "Inactive"},
//					},
//					Value: "draft",
//					AlpineModel: "formData.status",
//				},
//			},
//			Actions: []EnhancedFormAction{
//				{
//					ID:       "save-draft",
//					Type:     "save-draft",
//					Text:     "Save Draft",
//					Variant:  atoms.ButtonGhost,
//					Position: "left",
//				},
//				{
//					ID:       "cancel",
//					Type:     "cancel",
//					Text:     "Cancel",
//					Variant:  atoms.ButtonOutline,
//					Position: "right",
//				},
//				{
//					ID:       "submit",
//					Type:     "submit",
//					Text:     "Save Product",
//					Variant:  atoms.ButtonPrimary,
//					Position: "right",
//				},
//			},
//			InitialData: map[string]any{
//				"name":         "",
//				"sku":          "",
//				"category":     "",
//				"subcategory":  "",
//				"price":        "",
//				"salePrice":    "",
//				"stock":        "",
//				"weight":       "",
//				"description":  "",
//				"tags":         []string{},
//				"features":     []string{},
//				"status":       "draft",
//			},
//		})
//	}
//
// // ExampleSchemaForm demonstrates using the schema builder
//
//	templ ExampleSchemaForm(userSchema *schema.Schema) {
//		@EnhancedForm(CreateCRUDForm(userSchema).
//			WithTitle("User Management").
//			WithDescription("Create or edit user information").
//			WithValidationURL("/api/users/validate").
//			WithAutoSaveURL("/api/users/auto-save").
//			WithDebug(true).
//			Build())
//	}
//
// // ExampleReadOnlyForm demonstrates a read-only form for data display
//
//	templ ExampleReadOnlyForm() {
//		@EnhancedForm(EnhancedFormProps{
//			ID:          "user-profile",
//			Title:       "User Profile",
//			Description: "View user information",
//			Layout:      FormLayoutGrid,
//			GridCols:    2,
//			ReadOnly:    true,
//			Fields: []molecules.FormFieldProps{
//				{
//					ID:       "fullName",
//					Name:     "fullName",
//					Label:    "Full Name",
//					Type:     "text",
//					Value:    "John Doe",
//					Readonly: true,
//				},
//				{
//					ID:       "email",
//					Name:     "email",
//					Label:    "Email",
//					Type:     "email",
//					Value:    "john.doe@example.com",
//					Readonly: true,
//				},
//				{
//					ID:       "department",
//					Name:     "department",
//					Label:    "Department",
//					Type:     "text",
//					Value:    "Engineering",
//					Readonly: true,
//				},
//				{
//					ID:       "role",
//					Name:     "role",
//					Label:    "Role",
//					Type:     "text",
//					Value:    "Senior Developer",
//					Readonly: true,
//				},
//				{
//					ID:       "joinDate",
//					Name:     "joinDate",
//					Label:    "Join Date",
//					Type:     "date",
//					Value:    "2020-03-15",
//					Readonly: true,
//				},
//				{
//					ID:       "lastLogin",
//					Name:     "lastLogin",
//					Label:    "Last Login",
//					Type:     "text",
//					Value:    "2024-01-15 14:30:00",
//					Readonly: true,
//				},
//			},
//			Actions: []EnhancedFormAction{
//				{
//					ID:       "edit",
//					Type:     "button",
//					Text:     "Edit Profile",
//					Variant:  atoms.ButtonPrimary,
//					Position: "right",
//					OnClick:  "editProfile()",
//				},
//				{
//					ID:       "close",
//					Type:     "button",
//					Text:     "Close",
//					Variant:  atoms.ButtonOutline,
//					Position: "right",
//					OnClick:  "closeProfile()",
//				},
//			},
//		})
//	}
var _ = templruntime.GeneratedTemplate
