// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package organisms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/niiniyare/ruun/views/components/atoms"
	"strings"
)

// ModalSize defines the size variants for modals
type ModalSize string

const (
	ModalSizeXS   ModalSize = "xs"   // 320px
	ModalSizeSM   ModalSize = "sm"   // 384px
	ModalSizeMD   ModalSize = "md"   // 512px
	ModalSizeLG   ModalSize = "lg"   // 672px
	ModalSizeXL   ModalSize = "xl"   // 896px
	ModalSize2XL  ModalSize = "2xl"  // 1024px
	ModalSizeFull ModalSize = "full" // Full screen
)

// ModalVariant defines the visual style variants
type ModalVariant string

const (
	ModalDefault     ModalVariant = "default"
	ModalDestructive ModalVariant = "destructive"
	ModalSuccess     ModalVariant = "success"
	ModalWarning     ModalVariant = "warning"
)

// ModalAction represents a modal action button
type ModalAction struct {
	Text      string
	Variant   atoms.ButtonVariant
	Size      atoms.ButtonSize
	Icon      string
	IconLeft  string
	IconRight string
	Loading   bool
	Disabled  bool
	AutoClose bool // Whether clicking this action closes the modal
	Class     string
	ID        string
	// HTMX attributes
	HXPost   string
	HXGet    string
	HXTarget string
	HXSwap   string
	// Alpine.js attributes
	AlpineClick string
	// Events
	OnClick string
}

// ModalProps defines the properties for the Modal component
type ModalProps struct {
	Size           ModalSize
	Variant        ModalVariant
	Title          string
	Description    string
	Icon           string        // Icon for the header
	Actions        []ModalAction // Footer actions
	Dismissible    bool          // Whether modal can be dismissed
	CloseOnOverlay bool          // Whether clicking overlay closes modal
	CloseOnEscape  bool          // Whether pressing escape closes modal
	PersistOnClose bool          // Whether to keep modal in DOM when closed
	Backdrop       bool          // Whether to show backdrop
	Centered       bool          // Whether to center modal vertically
	Scrollable     bool          // Whether modal content is scrollable
	Class          string
	ID             string
	Name           string // For referencing in Alpine.js
	// Initial state
	Open bool
	// Content slots
	Header bool // Whether to show header
	Footer bool // Whether to show footer
	// HTMX attributes
	HXGet    string // URL to load content
	HXPost   string // URL for form submission
	HXTarget string // Target for HTMX responses
	HXSwap   string // HTMX swap strategy
	// Alpine.js attributes
	AlpineData string // Custom x-data
	AlpineShow string // Custom show condition
	// Events
	OnOpen        string // JavaScript function on open
	OnClose       string // JavaScript function on close
	OnBeforeClose string // JavaScript function before close (can prevent)
}

// modalClasses generates classes for the modal overlay
func modalClasses(props ModalProps) string {
	var classes []string

	// Base classes
	classes = append(classes,
		"fixed",
		"inset-0",
		"z-50",
		"flex",
		"items-center",
		"justify-center",
		"p-4",
	)

	// Backdrop
	if props.Backdrop {
		classes = append(classes, "bg-black/80")
	}

	// Centering
	if props.Centered {
		classes = append(classes, "items-center")
	} else {
		classes = append(classes, "items-start", "pt-16")
	}

	return strings.Join(classes, " ")
}

// modalContentClasses generates classes for the modal content container
func modalContentClasses(props ModalProps) string {
	var classes []string

	// Base classes
	classes = append(classes,
		"relative",
		"w-full",
		"rounded-lg",
		"border",
		"bg-background",
		"text-foreground",
		"shadow-lg",
		"focus:outline-none",
	)

	// Size classes
	switch props.Size {
	case ModalSizeXS:
		classes = append(classes, "max-w-xs")
	case ModalSizeSM:
		classes = append(classes, "max-w-sm")
	case ModalSizeMD:
		classes = append(classes, "max-w-md")
	case ModalSizeLG:
		classes = append(classes, "max-w-lg")
	case ModalSizeXL:
		classes = append(classes, "max-w-xl")
	case ModalSize2XL:
		classes = append(classes, "max-w-2xl")
	case ModalSizeFull:
		classes = append(classes, "w-screen", "h-screen", "max-w-none", "rounded-none")
	default:
		classes = append(classes, "max-w-md")
	}

	// Scrollable content
	if props.Scrollable {
		classes = append(classes, "max-h-[90vh]", "flex", "flex-col")
	}

	// Custom classes
	if props.Class != "" {
		classes = append(classes, props.Class)
	}

	return strings.Join(classes, " ")
}

// modalHeaderClasses generates classes for the modal header
func modalHeaderClasses(props ModalProps) string {
	var classes []string

	// Base classes
	classes = append(classes, "flex", "items-start", "justify-between", "p-6")

	// Variant-specific styling
	switch props.Variant {
	case ModalDestructive:
		classes = append(classes, "border-b", "border-destructive/20")
	case ModalSuccess:
		classes = append(classes, "border-b", "border-success/20")
	case ModalWarning:
		classes = append(classes, "border-b", "border-warning/20")
	default:
		classes = append(classes, "border-b")
	}

	return strings.Join(classes, " ")
}

// modalBodyClasses generates classes for the modal body
func modalBodyClasses(props ModalProps) string {
	var classes []string

	// Base classes
	classes = append(classes, "p-6")

	// Scrollable content
	if props.Scrollable {
		classes = append(classes, "overflow-y-auto", "flex-1")
	}

	return strings.Join(classes, " ")
}

// modalFooterClasses generates classes for the modal footer
func modalFooterClasses(props ModalProps) string {
	return strings.Join([]string{
		"flex", "items-center", "justify-end", "gap-2", "p-6", "border-t",
	}, " ")
}

// Modal renders a modal dialog component
func Modal(props ModalProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{modalClasses(props)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.ID != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 219, Col: 16}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.AlpineData != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " x-data=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(props.AlpineData)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 223, Col: 28}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " x-data=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(getDefaultModalAlpineData(props))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 225, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.AlpineShow != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " x-show=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(props.AlpineShow)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 228, Col: 28}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " else")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Name != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " x-show=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(props.Name + "Open")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 230, Col: 31}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, " x-show=\"open\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " x-transition:enter=\"ease-out duration-300\" x-transition:enter-start=\"opacity-0\" x-transition:enter-end=\"opacity-100\" x-transition:leave=\"ease-in duration-200\" x-transition:leave-start=\"opacity-100\" x-transition:leave-end=\"opacity-0\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.CloseOnEscape {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, " x-on:keydown.escape.window=\"closeModal()\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.CloseOnOverlay {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " x-on:click=\"closeModal()\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, " style=\"display: none;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 = []any{modalContentClasses(props)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var9...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var9).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\" x-transition:enter=\"ease-out duration-300\" x-transition:enter-start=\"opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95\" x-transition:enter-end=\"opacity-100 translate-y-0 sm:scale-100\" x-transition:leave=\"ease-in duration-200\" x-transition:leave-start=\"opacity-100 translate-y-0 sm:scale-100\" x-transition:leave-end=\"opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95\" x-on:click.stop")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.HXGet != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, " hx-get=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(props.HXGet)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 258, Col: 24}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "\" hx-target=\"this\" hx-swap=\"innerHTML\" hx-trigger=\"modalOpen\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Header || props.Title != "" || props.Dismissible {
			var templ_7745c5c3_Var12 = []any{modalHeaderClasses(props)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var12...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var12).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "\"><div class=\"flex items-start gap-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Icon != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<div class=\"shrink-0 mt-0.5\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = atoms.Icon(atoms.IconProps{
					Name:  props.Icon,
					Size:  atoms.IconSizeLG,
					Class: getHeaderIconClasses(props.Variant),
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "<div class=\"space-y-1\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Title != "" {
				var templ_7745c5c3_Var14 = []any{getHeaderTitleClasses(props.Variant)}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var14...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "<h2 class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var15 string
				templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var14).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var16 string
				templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 283, Col: 22}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "</h2>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if props.Description != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "<p class=\"text-sm text-muted-foreground\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var17 string
				templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(props.Description)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 288, Col: 28}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Dismissible {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "<button type=\"button\" class=\"rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none\" x-on:click=\"closeModal()\" aria-label=\"Close\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = atoms.Icon(atoms.IconProps{
					Name:  "x",
					Size:  atoms.IconSizeMD,
					Class: "h-4 w-4",
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		var templ_7745c5c3_Var18 = []any{modalBodyClasses(props)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var18...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var19 string
		templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var18).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.HXGet == "" {
			for _, child := range children {
				templ_7745c5c3_Err = child.Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, " <div class=\"flex items-center justify-center py-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.LoadingIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "<span class=\"ml-2 text-muted-foreground\">Loading...</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Footer || len(props.Actions) > 0 {
			var templ_7745c5c3_Var20 = []any{modalFooterClasses(props)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var20...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var21 string
			templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var20).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var21))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, action := range props.Actions {
				templ_7745c5c3_Err = modalAction(action, props).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// modalAction renders a modal action button
func modalAction(action ModalAction, modalProps ModalProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var22 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var22 == nil {
			templ_7745c5c3_Var22 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var23 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			var templ_7745c5c3_Var24 string
			templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.JoinStringErrs(action.Text)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/organisms/modal.templ`, Line: 358, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = atoms.Button(atoms.ButtonProps{
			Variant:     getModalActionVariant(action.Variant),
			Size:        getModalActionSize(action.Size),
			Icon:        action.Icon,
			IconLeft:    action.IconLeft,
			IconRight:   action.IconRight,
			Loading:     action.Loading,
			Disabled:    action.Disabled,
			Class:       action.Class,
			ID:          action.ID,
			HXPost:      action.HXPost,
			HXGet:       action.HXGet,
			HXTarget:    getModalActionTarget(action.HXTarget, modalProps.HXTarget),
			HXSwap:      getModalActionSwap(action.HXSwap, modalProps.HXSwap),
			AlpineClick: getModalActionClick(action.AlpineClick, action.AutoClose),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var23), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Convenience components for common modal types

// AlertModal renders an alert-style modal
func AlertModal(props ModalProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var25 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var25 == nil {
			templ_7745c5c3_Var25 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Modal(ModalProps{
			Size:           getAlertModalSize(props.Size),
			Variant:        props.Variant,
			Title:          props.Title,
			Description:    props.Description,
			Icon:           getAlertModalIcon(props.Icon, props.Variant),
			Actions:        getAlertModalActions(props.Actions, props.Variant),
			Dismissible:    props.Dismissible,
			CloseOnOverlay: props.CloseOnOverlay,
			CloseOnEscape:  props.CloseOnEscape,
			Header:         true,
			Footer:         true,
			Class:          props.Class,
			ID:             props.ID,
			Name:           props.Name,
			Open:           props.Open,
			AlpineData:     props.AlpineData,
			OnOpen:         props.OnOpen,
			OnClose:        props.OnClose,
			OnBeforeClose:  props.OnBeforeClose,
		}, children...).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ConfirmModal renders a confirmation modal
func ConfirmModal(props ModalProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var26 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var26 == nil {
			templ_7745c5c3_Var26 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Modal(ModalProps{
			Size:           getConfirmModalSize(props.Size),
			Variant:        getConfirmModalVariant(props.Variant),
			Title:          getConfirmModalTitle(props.Title),
			Description:    props.Description,
			Icon:           getConfirmModalIcon(props.Icon),
			Actions:        getConfirmModalActions(props.Actions),
			Dismissible:    props.Dismissible,
			CloseOnOverlay: props.CloseOnOverlay,
			CloseOnEscape:  getConfirmModalCloseOnEscape(props.CloseOnEscape),
			Header:         true,
			Footer:         true,
			Class:          props.Class,
			ID:             props.ID,
			Name:           props.Name,
			Open:           props.Open,
			AlpineData:     props.AlpineData,
			OnOpen:         props.OnOpen,
			OnClose:        props.OnClose,
			OnBeforeClose:  props.OnBeforeClose,
		}, children...).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// FormModal renders a modal with form content
func FormModal(props ModalProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var27 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var27 == nil {
			templ_7745c5c3_Var27 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Modal(ModalProps{
			Size:           getFormModalSize(props.Size),
			Variant:        props.Variant,
			Title:          props.Title,
			Description:    props.Description,
			Icon:           props.Icon,
			Actions:        props.Actions,
			Dismissible:    getFormModalDismissible(props.Dismissible),
			CloseOnOverlay: props.CloseOnOverlay,
			CloseOnEscape:  getFormModalCloseOnEscape(props.CloseOnEscape),
			Scrollable:     true,
			Header:         true,
			Footer:         len(props.Actions) > 0,
			Class:          props.Class,
			ID:             props.ID,
			Name:           props.Name,
			Open:           props.Open,
			HXGet:          props.HXGet,
			HXPost:         props.HXPost,
			HXTarget:       props.HXTarget,
			HXSwap:         props.HXSwap,
			AlpineData:     props.AlpineData,
			OnOpen:         props.OnOpen,
			OnClose:        props.OnClose,
			OnBeforeClose:  props.OnBeforeClose,
		}, children...).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// FullScreenModal renders a full-screen modal
func FullScreenModal(props ModalProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var28 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var28 == nil {
			templ_7745c5c3_Var28 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Modal(ModalProps{
			Size:           ModalSizeFull,
			Variant:        props.Variant,
			Title:          props.Title,
			Description:    props.Description,
			Icon:           props.Icon,
			Actions:        props.Actions,
			Dismissible:    getFullScreenModalDismissible(props.Dismissible),
			CloseOnOverlay: false,
			CloseOnEscape:  getFullScreenModalCloseOnEscape(props.CloseOnEscape),
			Scrollable:     true,
			Header:         true,
			Footer:         len(props.Actions) > 0,
			Class:          props.Class,
			ID:             props.ID,
			Name:           props.Name,
			Open:           props.Open,
			HXGet:          props.HXGet,
			HXPost:         props.HXPost,
			HXTarget:       props.HXTarget,
			HXSwap:         props.HXSwap,
			AlpineData:     props.AlpineData,
			OnOpen:         props.OnOpen,
			OnClose:        props.OnClose,
			OnBeforeClose:  props.OnBeforeClose,
		}, children...).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Helper functions for ternary operators
func getModalActionVariant(variant atoms.ButtonVariant) atoms.ButtonVariant {
	if variant != "" {
		return variant
	}
	return atoms.ButtonPrimary
}

func getModalActionSize(size atoms.ButtonSize) atoms.ButtonSize {
	if size != "" {
		return size
	}
	return atoms.ButtonSizeMD
}

func getModalActionTarget(actionTarget, modalTarget string) string {
	if actionTarget != "" {
		return actionTarget
	}
	return modalTarget
}

func getModalActionSwap(actionSwap, modalSwap string) string {
	if actionSwap != "" {
		return actionSwap
	}
	return modalSwap
}

func getModalActionClick(alpineClick string, autoClose bool) string {
	if autoClose {
		return alpineClick + "; closeModal()"
	}
	return alpineClick
}

func getAlertModalSize(size ModalSize) ModalSize {
	if size != "" {
		return size
	}
	return ModalSizeSM
}

func getAlertModalIcon(icon string, variant ModalVariant) string {
	if icon != "" {
		return icon
	}
	return getDefaultAlertIcon(variant)
}

func getAlertModalActions(actions []ModalAction, variant ModalVariant) []ModalAction {
	if len(actions) > 0 {
		return actions
	}
	return getDefaultAlertActions(variant)
}

func getConfirmModalSize(size ModalSize) ModalSize {
	if size != "" {
		return size
	}
	return ModalSizeSM
}

func getConfirmModalVariant(variant ModalVariant) ModalVariant {
	if variant != "" {
		return variant
	}
	return ModalWarning
}

func getConfirmModalTitle(title string) string {
	if title != "" {
		return title
	}
	return "Confirm Action"
}

func getConfirmModalIcon(icon string) string {
	if icon != "" {
		return icon
	}
	return "alert-triangle"
}

func getConfirmModalActions(actions []ModalAction) []ModalAction {
	if len(actions) > 0 {
		return actions
	}
	return getDefaultConfirmActions()
}

func getConfirmModalCloseOnEscape(closeOnEscape bool) bool {
	// Default to true for confirm modals
	return true
}

func getFormModalSize(size ModalSize) ModalSize {
	if size != "" {
		return size
	}
	return ModalSizeLG
}

func getFormModalDismissible(dismissible bool) bool {
	// Default to true for form modals
	return true
}

func getFormModalCloseOnEscape(closeOnEscape bool) bool {
	// Default to true for form modals
	return true
}

func getFullScreenModalDismissible(dismissible bool) bool {
	// Default to true for fullscreen modals
	return true
}

func getFullScreenModalCloseOnEscape(closeOnEscape bool) bool {
	// Default to true for fullscreen modals
	return true
}

func getModalOpenValue(open bool) string {
	if open {
		return "true"
	}
	return "false"
}

// Helper functions

func getDefaultModalAlpineData(props ModalProps) string {
	openVar := "open"
	if props.Name != "" {
		openVar = props.Name + "Open"
	}

	return `{
		` + openVar + `: ` + getModalOpenValue(props.Open) + `,
		
		openModal() {
			this.` + openVar + ` = true;
			document.body.style.overflow = 'hidden';
			` + props.OnOpen + `
		},
		
		closeModal() {
			if (this.beforeClose && !this.beforeClose()) {
				return;
			}
			this.` + openVar + ` = false;
			document.body.style.overflow = '';
			` + props.OnClose + `
		},
		
		beforeClose() {
			` + props.OnBeforeClose + `
			return true;
		}
	}`
}

func getHeaderIconClasses(variant ModalVariant) string {
	switch variant {
	case ModalDestructive:
		return "text-destructive"
	case ModalSuccess:
		return "text-success"
	case ModalWarning:
		return "text-warning"
	default:
		return "text-muted-foreground"
	}
}

func getHeaderTitleClasses(variant ModalVariant) string {
	classes := []string{"text-lg", "font-semibold"}

	switch variant {
	case ModalDestructive:
		classes = append(classes, "text-destructive")
	case ModalSuccess:
		classes = append(classes, "text-success")
	case ModalWarning:
		classes = append(classes, "text-warning")
	default:
		classes = append(classes, "text-foreground")
	}

	return strings.Join(classes, " ")
}

func getDefaultAlertIcon(variant ModalVariant) string {
	switch variant {
	case ModalDestructive:
		return "alert-circle"
	case ModalSuccess:
		return "check"
	case ModalWarning:
		return "alert-triangle"
	default:
		return "info"
	}
}

func getDefaultAlertActions(variant ModalVariant) []ModalAction {
	actions := []ModalAction{
		{
			Text:      "OK",
			Variant:   atoms.ButtonPrimary,
			AutoClose: true,
		},
	}

	if variant == ModalDestructive {
		actions[0].Variant = atoms.ButtonDestructive
	}

	return actions
}

func getDefaultConfirmActions() []ModalAction {
	return []ModalAction{
		{
			Text:      "Cancel",
			Variant:   atoms.ButtonOutline,
			AutoClose: true,
		},
		{
			Text:      "Confirm",
			Variant:   atoms.ButtonPrimary,
			AutoClose: true,
		},
	}
}

var _ = templruntime.GeneratedTemplate
