// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package atoms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// BadgeVariant defines the visual style variants for badges
type BadgeVariant string

const (
	BadgeDefault     BadgeVariant = "default"
	BadgeSecondary   BadgeVariant = "secondary"
	BadgeSuccess     BadgeVariant = "success"
	BadgeWarning     BadgeVariant = "warning"
	BadgeDestructive BadgeVariant = "destructive"
	BadgeOutline     BadgeVariant = "outline"
)

// BadgeSize defines the size variants for badges
type BadgeSize string

const (
	BadgeSizeSM BadgeSize = "sm"
	BadgeSizeMD BadgeSize = "md"
	BadgeSizeLG BadgeSize = "lg"
)

// BadgeMode represents the badge display mode (for overlay badges)
type BadgeMode string

const (
	BadgeModeText   BadgeMode = "text"
	BadgeModeDot    BadgeMode = "dot"
	BadgeModeRibbon BadgeMode = "ribbon"
)

// BadgePosition represents the corner position (for overlay badges)
type BadgePosition string

const (
	BadgePositionTopRight    BadgePosition = "top-right"
	BadgePositionTopLeft     BadgePosition = "top-left"
	BadgePositionBottomRight BadgePosition = "bottom-right"
	BadgePositionBottomLeft  BadgePosition = "bottom-left"
)

// BadgeProps defines the properties for the unified Badge component
type BadgeProps struct {
	// Styling (follows badge.templ)
	Variant BadgeVariant
	Size    BadgeSize
	Class   string
	ID      string

	// Content
	Text      any    // Text content (string or number) - for overlay badges
	Icon      string // Single icon (for icon-only badges)
	IconLeft  string
	IconRight string

	// Overlay/Position features (from badge.new.templ)
	Mode          BadgeMode     // Badge mode: text, dot, ribbon (for overlays)
	Position      BadgePosition // Corner position (for overlays)
	Offset        []any         // Position offset [x, y]
	OverflowCount int           // Max count before showing "+"

	// Interactivity
	Removable bool
	OnRemove  string // Alpine.js remove handler
	Animation bool   // Enable pulse animation
	VisibleOn string // Alpine.js condition for visibility

	// HTMX attributes
	HXPost    string
	HXGet     string
	HXTarget  string
	HXSwap    string
	HXTrigger string

	// Alpine.js attributes
	AlpineClick string

	// Custom styling
	Style string // Custom inline styles
}

// GetText returns the display text with overflow handling
func (p BadgeProps) GetText() string {
	if p.Text == nil {
		return ""
	}

	// Handle numeric overflow
	if num, ok := p.Text.(int); ok {
		if p.OverflowCount > 0 && num > p.OverflowCount {
			return fmt.Sprintf("%d+", p.OverflowCount)
		}
		return strconv.Itoa(num)
	}

	if num, ok := p.Text.(float64); ok {
		intNum := int(num)
		if p.OverflowCount > 0 && intNum > p.OverflowCount {
			return fmt.Sprintf("%d+", p.OverflowCount)
		}
		return strconv.Itoa(intNum)
	}

	return fmt.Sprint(p.Text)
}

// GetPositionClasses returns Tailwind classes for positioning (overlay mode)
func (p BadgeProps) GetPositionClasses() string {
	switch p.Position {
	case BadgePositionTopRight:
		return "top-0 right-0 -translate-y-1/2 translate-x-1/2"
	case BadgePositionTopLeft:
		return "top-0 left-0 -translate-y-1/2 -translate-x-1/2"
	case BadgePositionBottomRight:
		return "bottom-0 right-0 translate-y-1/2 translate-x-1/2"
	case BadgePositionBottomLeft:
		return "bottom-0 left-0 translate-y-1/2 -translate-x-1/2"
	default:
		return "top-0 right-0 -translate-y-1/2 translate-x-1/2"
	}
}

// GetOffsetStyle returns CSS transform for offset positioning
func (p BadgeProps) GetOffsetStyle() string {
	if len(p.Offset) != 2 {
		return ""
	}

	x := p.formatOffsetValue(p.Offset[0])
	y := p.formatOffsetValue(p.Offset[1])

	return fmt.Sprintf("transform: translate(%s, %s);", x, y)
}

func (p BadgeProps) formatOffsetValue(val any) string {
	switch v := val.(type) {
	case int:
		return fmt.Sprintf("%dpx", v)
	case float64:
		return fmt.Sprintf("%dpx", int(v))
	case string:
		return v
	default:
		return "0"
	}
}

// badgeClasses generates Tailwind CSS classes for the badge
func badgeClasses(props BadgeProps) string {
	var classes []string

	// Base classes
	classes = append(classes,
		"inline-flex",
		"items-center",
		"justify-center",
		"rounded-full",
		"border",
		"font-semibold",
		"transition-colors",
		"focus:outline-none",
		"focus:ring-2",
		"focus:ring-ring",
		"focus:ring-offset-2",
	)

	// Mode-specific classes (for overlay badges)
	if props.Mode == BadgeModeDot {
		classes = append(classes, "w-2", "h-2")
	} else if props.Mode == BadgeModeRibbon {
		classes = append(classes, "px-3", "py-1", "text-xs", "font-medium")
	} else {
		// Size classes (for normal badges)
		switch props.Size {
		case BadgeSizeSM:
			classes = append(classes, "px-2", "py-0.5", "text-xs")
		case BadgeSizeMD:
			classes = append(classes, "px-2.5", "py-0.5", "text-xs")
		case BadgeSizeLG:
			classes = append(classes, "px-3", "py-1", "text-sm")
		default:
			classes = append(classes, "px-2.5", "py-0.5", "text-xs")
		}

		// Add min-width for text badges
		if props.Mode == BadgeModeText || props.Mode == "" {
			classes = append(classes, "min-w-[20px]", "text-center")
		}
	}

	// Variant classes (follows badge.templ styling)
	switch props.Variant {
	case BadgeDefault:
		classes = append(classes, "border-transparent", "bg-primary", "text-primary-foreground", "hover:bg-primary/80")
	case BadgeSecondary:
		classes = append(classes, "border-transparent", "bg-secondary", "text-secondary-foreground", "hover:bg-secondary/80")
	case BadgeSuccess:
		classes = append(classes, "border-transparent", "bg-success", "text-success-foreground", "hover:bg-success/80")
	case BadgeWarning:
		classes = append(classes, "border-transparent", "bg-warning", "text-warning-foreground", "hover:bg-warning/80")
	case BadgeDestructive:
		classes = append(classes, "border-transparent", "bg-destructive", "text-destructive-foreground", "hover:bg-destructive/80")
	case BadgeOutline:
		classes = append(classes, "text-foreground")
	default:
		classes = append(classes, "border-transparent", "bg-primary", "text-primary-foreground", "hover:bg-primary/80")
	}

	// Animation classes
	if props.Animation {
		classes = append(classes, "animate-pulse")
	}

	// Interactive classes
	if props.HXPost != "" || props.HXGet != "" || props.AlpineClick != "" {
		classes = append(classes, "cursor-pointer")
	}

	// Custom classes
	if props.Class != "" {
		classes = append(classes, props.Class)
	}

	return strings.Join(classes, " ")
}

// Badge renders a unified badge component
func Badge(props BadgeProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props.HXPost != "" || props.HXGet != "" || props.AlpineClick != "" {
			var templ_7745c5c3_Var2 = []any{badgeClasses(props)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.ID != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " id=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.ID)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 240, Col: 17}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.VisibleOn != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " x-show=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(props.VisibleOn)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 244, Col: 28}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(props.Style)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 246, Col: 22}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.HXPost != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " hx-post=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(props.HXPost)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 248, Col: 26}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if props.HXGet != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " hx-get=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(props.HXGet)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 251, Col: 24}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if props.HXTarget != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, " hx-target=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var9 string
				templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(props.HXTarget)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 254, Col: 30}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if props.HXSwap != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " hx-swap=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var10 string
				templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(props.HXSwap)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 257, Col: 26}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if props.HXTrigger != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " hx-trigger=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var11 string
				templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(props.HXTrigger)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 260, Col: 32}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if props.AlpineClick != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, " x-on:click=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var12 string
				templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(props.AlpineClick)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 263, Col: 34}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = badgeContent(props, children...).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			var templ_7745c5c3_Var13 = []any{badgeClasses(props)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var13...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "<span")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.ID != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, " id=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var14 string
				templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(props.ID)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 271, Col: 17}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, " class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var15 string
			templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var13).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.VisibleOn != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, " x-show=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var16 string
				templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(props.VisibleOn)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 275, Col: 28}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, " style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var17 string
			templ_7745c5c3_Var17, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(props.Style)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 277, Col: 22}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = badgeContent(props, children...).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// badgeContent renders the internal content of the badge
func badgeContent(props BadgeProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var18 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var18 == nil {
			templ_7745c5c3_Var18 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props.Mode == BadgeModeDot {
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.IconLeft != "" {
				templ_7745c5c3_Err = Icon(IconProps{Name: props.IconLeft, Size: IconSizeXS, ClassName: "mr-1"}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "  ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Icon != "" && len(children) == 0 && props.Text == nil {
				templ_7745c5c3_Err = Icon(IconProps{Name: props.Icon, Size: IconSizeXS}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "  ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Text != nil {
				var templ_7745c5c3_Var19 string
				templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(props.GetText())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 302, Col: 20}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, child := range children {
				templ_7745c5c3_Err = child.Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "  ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.IconRight != "" {
				templ_7745c5c3_Err = Icon(IconProps{Name: props.IconRight, Size: IconSizeXS, ClassName: "ml-1"}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "  ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Removable {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "<button type=\"button\" class=\"ml-1 h-3 w-3 rounded-full outline-none ring-offset-background transition-colors hover:bg-secondary-foreground/20 focus:bg-secondary-foreground/20 focus:ring-2 focus:ring-ring focus:ring-offset-1\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if props.OnRemove != "" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, " x-on:click=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var20 string
					templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.JoinStringErrs(props.OnRemove)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 321, Col: 32}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var20))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, " aria-label=\"Remove\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = Icon(IconProps{Name: "x", Size: IconSizeXS}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "</button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		return nil
	})
}

// BadgeWrapper wraps content with a positioned badge (for overlay/notification badges)
func BadgeWrapper(content templ.Component, badge BadgeProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var21 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var21 == nil {
			templ_7745c5c3_Var21 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "<div class=\"relative inline-block\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var22 = []any{"absolute",
			badge.GetPositionClasses(),
		}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var22...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var23 string
		templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var22).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if badge.GetOffsetStyle() != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 48, " style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var24 string
			templ_7745c5c3_Var24, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(badge.GetOffsetStyle())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 341, Col: 34}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 49, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 50, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Badge(badge).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 51, "</span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Convenience components for common badge variants
func DefaultBadge(props BadgeProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var25 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var25 == nil {
			templ_7745c5c3_Var25 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Badge(BadgeProps{
			Variant:       BadgeDefault,
			Size:          props.Size,
			Icon:          props.Icon,
			IconLeft:      props.IconLeft,
			IconRight:     props.IconRight,
			Class:         props.Class,
			ID:            props.ID,
			Removable:     props.Removable,
			OnRemove:      props.OnRemove,
			HXPost:        props.HXPost,
			HXGet:         props.HXGet,
			HXTarget:      props.HXTarget,
			HXSwap:        props.HXSwap,
			HXTrigger:     props.HXTrigger,
			AlpineClick:   props.AlpineClick,
			Text:          props.Text,
			Mode:          props.Mode,
			Position:      props.Position,
			Offset:        props.Offset,
			OverflowCount: props.OverflowCount,
			Animation:     props.Animation,
			VisibleOn:     props.VisibleOn,
			Style:         props.Style,
		}, children...).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SuccessBadge(props BadgeProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var26 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var26 == nil {
			templ_7745c5c3_Var26 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Badge(BadgeProps{
			Variant:       BadgeSuccess,
			Size:          props.Size,
			Icon:          props.Icon,
			IconLeft:      props.IconLeft,
			IconRight:     props.IconRight,
			Class:         props.Class,
			ID:            props.ID,
			Removable:     props.Removable,
			OnRemove:      props.OnRemove,
			HXPost:        props.HXPost,
			HXGet:         props.HXGet,
			HXTarget:      props.HXTarget,
			HXSwap:        props.HXSwap,
			HXTrigger:     props.HXTrigger,
			AlpineClick:   props.AlpineClick,
			Text:          props.Text,
			Mode:          props.Mode,
			Position:      props.Position,
			Offset:        props.Offset,
			OverflowCount: props.OverflowCount,
			Animation:     props.Animation,
			VisibleOn:     props.VisibleOn,
			Style:         props.Style,
		}, children...).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func WarningBadge(props BadgeProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var27 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var27 == nil {
			templ_7745c5c3_Var27 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Badge(BadgeProps{
			Variant:       BadgeWarning,
			Size:          props.Size,
			Icon:          props.Icon,
			IconLeft:      props.IconLeft,
			IconRight:     props.IconRight,
			Class:         props.Class,
			ID:            props.ID,
			Removable:     props.Removable,
			OnRemove:      props.OnRemove,
			HXPost:        props.HXPost,
			HXGet:         props.HXGet,
			HXTarget:      props.HXTarget,
			HXSwap:        props.HXSwap,
			HXTrigger:     props.HXTrigger,
			AlpineClick:   props.AlpineClick,
			Text:          props.Text,
			Mode:          props.Mode,
			Position:      props.Position,
			Offset:        props.Offset,
			OverflowCount: props.OverflowCount,
			Animation:     props.Animation,
			VisibleOn:     props.VisibleOn,
			Style:         props.Style,
		}, children...).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func DestructiveBadge(props BadgeProps, children ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var28 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var28 == nil {
			templ_7745c5c3_Var28 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Badge(BadgeProps{
			Variant:       BadgeDestructive,
			Size:          props.Size,
			Icon:          props.Icon,
			IconLeft:      props.IconLeft,
			IconRight:     props.IconRight,
			Class:         props.Class,
			ID:            props.ID,
			Removable:     props.Removable,
			OnRemove:      props.OnRemove,
			HXPost:        props.HXPost,
			HXGet:         props.HXGet,
			HXTarget:      props.HXTarget,
			HXSwap:        props.HXSwap,
			HXTrigger:     props.HXTrigger,
			AlpineClick:   props.AlpineClick,
			Text:          props.Text,
			Mode:          props.Mode,
			Position:      props.Position,
			Offset:        props.Offset,
			OverflowCount: props.OverflowCount,
			Animation:     props.Animation,
			VisibleOn:     props.VisibleOn,
			Style:         props.Style,
		}, children...).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// JSON Schema Support (from badge.new.templ)

// BadgeSchema represents the JSON schema for Badge component
type BadgeSchema struct {
	Variant       string `json:"variant,omitempty"`
	Size          string `json:"size,omitempty"`
	Class         string `json:"class,omitempty"`
	Text          any    `json:"text,omitempty"`
	Icon          string `json:"icon,omitempty"`
	IconLeft      string `json:"iconLeft,omitempty"`
	IconRight     string `json:"iconRight,omitempty"`
	Mode          string `json:"mode,omitempty"`
	Position      string `json:"position,omitempty"`
	Offset        []any  `json:"offset,omitempty"`
	OverflowCount int    `json:"overflowCount,omitempty"`
	VisibleOn     string `json:"visibleOn,omitempty"`
	Animation     bool   `json:"animation,omitempty"`
	Style         string `json:"style,omitempty"`
	Removable     bool   `json:"removable,omitempty"`
}

// ToProps converts BadgeSchema to BadgeProps
func (s BadgeSchema) ToProps() BadgeProps {
	props := BadgeProps{
		Class:         s.Class,
		Text:          s.Text,
		Icon:          s.Icon,
		IconLeft:      s.IconLeft,
		IconRight:     s.IconRight,
		Offset:        s.Offset,
		OverflowCount: s.OverflowCount,
		VisibleOn:     s.VisibleOn,
		Animation:     s.Animation,
		Style:         s.Style,
		Removable:     s.Removable,
	}

	// Convert variant string to BadgeVariant
	switch s.Variant {
	case "default":
		props.Variant = BadgeDefault
	case "secondary":
		props.Variant = BadgeSecondary
	case "success":
		props.Variant = BadgeSuccess
	case "warning":
		props.Variant = BadgeWarning
	case "destructive":
		props.Variant = BadgeDestructive
	case "outline":
		props.Variant = BadgeOutline
	default:
		props.Variant = BadgeDefault
	}

	// Convert size string to BadgeSize
	switch s.Size {
	case "sm":
		props.Size = BadgeSizeSM
	case "md":
		props.Size = BadgeSizeMD
	case "lg":
		props.Size = BadgeSizeLG
	default:
		props.Size = BadgeSizeMD
	}

	// Convert mode string to BadgeMode
	switch s.Mode {
	case "text":
		props.Mode = BadgeModeText
	case "dot":
		props.Mode = BadgeModeDot
	case "ribbon":
		props.Mode = BadgeModeRibbon
	default:
		props.Mode = BadgeModeText
	}

	// Convert position string to BadgePosition
	switch s.Position {
	case "top-right":
		props.Position = BadgePositionTopRight
	case "top-left":
		props.Position = BadgePositionTopLeft
	case "bottom-right":
		props.Position = BadgePositionBottomRight
	case "bottom-left":
		props.Position = BadgePositionBottomLeft
	default:
		props.Position = BadgePositionTopRight
	}

	return props
}

// BadgeFromJSON creates a Badge component from JSON string
func BadgeFromJSON(jsonStr string) (BadgeProps, error) {
	var schema BadgeSchema
	if err := json.Unmarshal([]byte(jsonStr), &schema); err != nil {
		return BadgeProps{}, fmt.Errorf("failed to unmarshal badge JSON: %w", err)
	}
	return schema.ToProps(), nil
}

// Example JSON configurations
const (
	ExampleNotificationBadge = `{
		"text": 5,
		"mode": "text",
		"position": "top-right",
		"variant": "destructive",
		"animation": true
	}`

	ExampleOverflowBadge = `{
		"text": 150,
		"mode": "text",
		"position": "top-right",
		"overflowCount": 99,
		"variant": "default"
	}`

	ExampleStatusDot = `{
		"mode": "dot",
		"position": "bottom-right",
		"variant": "success"
	}`

	ExampleDynamicBadge = `{
		"text": 3,
		"mode": "text",
		"position": "top-right",
		"visibleOn": "unreadCount > 0",
		"variant": "destructive"
	}`

	ExampleCustomOffsetBadge = `{
		"text": "NEW",
		"mode": "text",
		"position": "top-right",
		"offset": [10, -5],
		"variant": "success"
	}`
)

// BadgeFrom renders a Badge from JSON schema at runtime
func BadgeFrom(schemaJSON string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var29 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var29 == nil {
			templ_7745c5c3_Var29 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props, err := BadgeFromJSON(schemaJSON); err == nil {
			templ_7745c5c3_Err = Badge(props).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 52, "<span class=\"text-red-500 text-xs\">Invalid badge schema: ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var30 string
			templ_7745c5c3_Var30, templ_7745c5c3_Err = templ.JoinStringErrs(err.Error())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/badge.templ`, Line: 614, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var30))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 53, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// Fluent API Builder Pattern

// BadgeBuilder provides a fluent interface for building badges
type BadgeBuilder struct {
	props BadgeProps
}

// NewBadge creates a new badge builder with default values
func NewBadge() *BadgeBuilder {
	return &BadgeBuilder{
		props: BadgeProps{
			Variant: BadgeDefault,
			Size:    BadgeSizeMD,
		},
	}
}

// Styling methods
func (b *BadgeBuilder) Default() *BadgeBuilder {
	b.props.Variant = BadgeDefault
	return b
}

func (b *BadgeBuilder) Secondary() *BadgeBuilder {
	b.props.Variant = BadgeSecondary
	return b
}

func (b *BadgeBuilder) Success() *BadgeBuilder {
	b.props.Variant = BadgeSuccess
	return b
}

func (b *BadgeBuilder) Warning() *BadgeBuilder {
	b.props.Variant = BadgeWarning
	return b
}

func (b *BadgeBuilder) Destructive() *BadgeBuilder {
	b.props.Variant = BadgeDestructive
	return b
}

func (b *BadgeBuilder) Outline() *BadgeBuilder {
	b.props.Variant = BadgeOutline
	return b
}

func (b *BadgeBuilder) Small() *BadgeBuilder {
	b.props.Size = BadgeSizeSM
	return b
}

func (b *BadgeBuilder) Medium() *BadgeBuilder {
	b.props.Size = BadgeSizeMD
	return b
}

func (b *BadgeBuilder) Large() *BadgeBuilder {
	b.props.Size = BadgeSizeLG
	return b
}

// Content methods
func (b *BadgeBuilder) WithText(text any) *BadgeBuilder {
	b.props.Text = text
	return b
}

func (b *BadgeBuilder) WithIcon(icon string) *BadgeBuilder {
	b.props.Icon = icon
	return b
}

func (b *BadgeBuilder) WithIconLeft(icon string) *BadgeBuilder {
	b.props.IconLeft = icon
	return b
}

func (b *BadgeBuilder) WithIconRight(icon string) *BadgeBuilder {
	b.props.IconRight = icon
	return b
}

func (b *BadgeBuilder) WithClass(class string) *BadgeBuilder {
	b.props.Class = class
	return b
}

func (b *BadgeBuilder) WithID(id string) *BadgeBuilder {
	b.props.ID = id
	return b
}

func (b *BadgeBuilder) WithStyle(style string) *BadgeBuilder {
	b.props.Style = style
	return b
}

// Overlay/Position methods
func (b *BadgeBuilder) AsText() *BadgeBuilder {
	b.props.Mode = BadgeModeText
	return b
}

func (b *BadgeBuilder) AsDot() *BadgeBuilder {
	b.props.Mode = BadgeModeDot
	return b
}

func (b *BadgeBuilder) AsRibbon() *BadgeBuilder {
	b.props.Mode = BadgeModeRibbon
	return b
}

func (b *BadgeBuilder) TopRight() *BadgeBuilder {
	b.props.Position = BadgePositionTopRight
	return b
}

func (b *BadgeBuilder) TopLeft() *BadgeBuilder {
	b.props.Position = BadgePositionTopLeft
	return b
}

func (b *BadgeBuilder) BottomRight() *BadgeBuilder {
	b.props.Position = BadgePositionBottomRight
	return b
}

func (b *BadgeBuilder) BottomLeft() *BadgeBuilder {
	b.props.Position = BadgePositionBottomLeft
	return b
}

func (b *BadgeBuilder) WithOffset(x, y any) *BadgeBuilder {
	b.props.Offset = []any{x, y}
	return b
}

func (b *BadgeBuilder) WithOverflowCount(count int) *BadgeBuilder {
	b.props.OverflowCount = count
	return b
}

// Interactivity methods
func (b *BadgeBuilder) Removable(onRemove string) *BadgeBuilder {
	b.props.Removable = true
	b.props.OnRemove = onRemove
	return b
}

func (b *BadgeBuilder) Animated() *BadgeBuilder {
	b.props.Animation = true
	return b
}

func (b *BadgeBuilder) VisibleWhen(condition string) *BadgeBuilder {
	b.props.VisibleOn = condition
	return b
}

// HTMX methods
func (b *BadgeBuilder) HXPost(url string) *BadgeBuilder {
	b.props.HXPost = url
	return b
}

func (b *BadgeBuilder) HXGet(url string) *BadgeBuilder {
	b.props.HXGet = url
	return b
}

func (b *BadgeBuilder) HXTarget(target string) *BadgeBuilder {
	b.props.HXTarget = target
	return b
}

func (b *BadgeBuilder) HXSwap(swap string) *BadgeBuilder {
	b.props.HXSwap = swap
	return b
}

func (b *BadgeBuilder) HXTrigger(trigger string) *BadgeBuilder {
	b.props.HXTrigger = trigger
	return b
}

// Alpine.js methods
func (b *BadgeBuilder) OnClick(handler string) *BadgeBuilder {
	b.props.AlpineClick = handler
	return b
}

// Build returns the final BadgeProps
func (b *BadgeBuilder) Build() BadgeProps {
	return b.props
}

// Functional Options Pattern (alternative to fluent API)

// BadgeOption is a function that modifies BadgeProps
type BadgeOption func(*BadgeProps)

// NewBadgeWithOptions creates a BadgeProps with functional options
func NewBadgeWithOptions(opts ...BadgeOption) BadgeProps {
	props := BadgeProps{
		Variant: BadgeDefault,
		Size:    BadgeSizeMD,
	}
	for _, opt := range opts {
		opt(&props)
	}
	return props
}

// Variant options
func WithBadgeVariant(variant BadgeVariant) BadgeOption {
	return func(p *BadgeProps) { p.Variant = variant }
}

func WithDefault() BadgeOption {
	return func(p *BadgeProps) { p.Variant = BadgeDefault }
}

func WithSecondary() BadgeOption {
	return func(p *BadgeProps) { p.Variant = BadgeSecondary }
}

func WithSuccess() BadgeOption {
	return func(p *BadgeProps) { p.Variant = BadgeSuccess }
}

func WithWarning() BadgeOption {
	return func(p *BadgeProps) { p.Variant = BadgeWarning }
}

func WithDestructive() BadgeOption {
	return func(p *BadgeProps) { p.Variant = BadgeDestructive }
}

func WithOutline() BadgeOption {
	return func(p *BadgeProps) { p.Variant = BadgeOutline }
}

// Size options
func WithBadgeSize(size BadgeSize) BadgeOption {
	return func(p *BadgeProps) { p.Size = size }
}

func WithSmall() BadgeOption {
	return func(p *BadgeProps) { p.Size = BadgeSizeSM }
}

func WithMedium() BadgeOption {
	return func(p *BadgeProps) { p.Size = BadgeSizeMD }
}

func WithLarge() BadgeOption {
	return func(p *BadgeProps) { p.Size = BadgeSizeLG }
}

// Content options
func WithBadgeText(text any) BadgeOption {
	return func(p *BadgeProps) { p.Text = text }
}

func WithBadgeIcon(icon string) BadgeOption {
	return func(p *BadgeProps) { p.Icon = icon }
}

func WithBadgeIconLeft(icon string) BadgeOption {
	return func(p *BadgeProps) { p.IconLeft = icon }
}

func WithBadgeIconRight(icon string) BadgeOption {
	return func(p *BadgeProps) { p.IconRight = icon }
}

func WithBadgeClass(class string) BadgeOption {
	return func(p *BadgeProps) { p.Class = class }
}

func WithBadgeID(id string) BadgeOption {
	return func(p *BadgeProps) { p.ID = id }
}

func WithStyle(style string) BadgeOption {
	return func(p *BadgeProps) { p.Style = style }
}

// Mode options
func WithMode(mode BadgeMode) BadgeOption {
	return func(p *BadgeProps) { p.Mode = mode }
}

func AsTextMode() BadgeOption {
	return func(p *BadgeProps) { p.Mode = BadgeModeText }
}

func AsDotMode() BadgeOption {
	return func(p *BadgeProps) { p.Mode = BadgeModeDot }
}

func AsRibbonMode() BadgeOption {
	return func(p *BadgeProps) { p.Mode = BadgeModeRibbon }
}

// Position options
func WithPosition(position BadgePosition) BadgeOption {
	return func(p *BadgeProps) { p.Position = position }
}

func AtTopRight() BadgeOption {
	return func(p *BadgeProps) { p.Position = BadgePositionTopRight }
}

func AtTopLeft() BadgeOption {
	return func(p *BadgeProps) { p.Position = BadgePositionTopLeft }
}

func AtBottomRight() BadgeOption {
	return func(p *BadgeProps) { p.Position = BadgePositionBottomRight }
}

func AtBottomLeft() BadgeOption {
	return func(p *BadgeProps) { p.Position = BadgePositionBottomLeft }
}

func WithOffset(x, y any) BadgeOption {
	return func(p *BadgeProps) { p.Offset = []any{x, y} }
}

func WithOverflowCount(count int) BadgeOption {
	return func(p *BadgeProps) { p.OverflowCount = count }
}

// Interactivity options
func AsRemovable(onRemove string) BadgeOption {
	return func(p *BadgeProps) {
		p.Removable = true
		p.OnRemove = onRemove
	}
}

func WithAnimation() BadgeOption {
	return func(p *BadgeProps) { p.Animation = true }
}

func VisibleWhen(condition string) BadgeOption {
	return func(p *BadgeProps) { p.VisibleOn = condition }
}

// HTMX options
func WithBadgeHXPost(url string) BadgeOption {
	return func(p *BadgeProps) { p.HXPost = url }
}

func WithBadgeHXGet(url string) BadgeOption {
	return func(p *BadgeProps) { p.HXGet = url }
}

func WithBadgeHXTarget(target string) BadgeOption {
	return func(p *BadgeProps) { p.HXTarget = target }
}

func WithBadgeHXSwap(swap string) BadgeOption {
	return func(p *BadgeProps) { p.HXSwap = swap }
}

func WithBadgeHXTrigger(trigger string) BadgeOption {
	return func(p *BadgeProps) { p.HXTrigger = trigger }
}

// Alpine.js options
func WithBadgeAlpineClick(handler string) BadgeOption {
	return func(p *BadgeProps) { p.AlpineClick = handler }
}

// Key Improvements in this refactored version:
// 1. Pure Presentation: No business logic, just visual rendering
// 2. Compiled Theme Classes: Uses "badge", "badge-primary", etc. from compiled CSS
// 3. Utils Integration: TwMerge for class conflicts, If for conditionals
// 4. Clean Props Interface: Focused on presentation concerns only
// 5. Multiple Patterns: Fluent API, Functional Options, and JSON Schema support
// 6. Atomic Design Compliant: Single purpose, indivisible badge component
// 7. Icon Integration: Uses Icon atom for consistent iconography
// 8. Ready for Molecules: Can be easily composed into notification systems
// 9. Overlay Support: Built-in positioning for notification badges
// 10. Accessibility: Proper ARIA labels and semantic markup
var _ = templruntime.GeneratedTemplate
