// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package atoms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strconv"

// Note: Tags use Basecoat badge classes for styling
// Available variants: primary, secondary, destructive, outline
// State handled via data attributes and HTML attributes

// TagProps defines all properties for the Tag atom using Basecoat badge classes
type TagProps struct {
	// Core attributes
	ID    string `json:"id"`
	Text  string `json:"text"`
	Value string `json:"value"`

	// Basecoat badge variants only
	Variant string `json:"variant,omitempty"` // "primary", "secondary", "destructive", "outline"

	// Icon configuration
	Icon      templ.Component `json:"icon,omitempty"`
	IconLeft  templ.Component `json:"iconLeft,omitempty"`
	IconRight templ.Component `json:"iconRight,omitempty"`

	// Interactive features
	Selected  bool `json:"selected,omitempty"`
	Removable bool `json:"removable,omitempty"`
	Clickable bool `json:"clickable,omitempty"`
	Disabled  bool `json:"disabled,omitempty"`

	// Event handlers (pre-resolved externally)
	OnClick  string `json:"onClick"`
	OnRemove string `json:"onRemove"`
	OnHover  string `json:"onHover"`

	// ARIA accessibility attributes
	AriaLabel       string `json:"ariaLabel"`
	AriaDescribedBy string `json:"ariaDescribedBy"`
	AriaPressed     string `json:"ariaPressed"`
	AriaSelected    string `json:"ariaSelected"`

	// Additional HTML attributes
	TabIndex   int               `json:"tabIndex"`
	DataAttrs  map[string]string `json:"dataAttrs"`
	Attributes templ.Attributes  `json:"attributes"`
}

// getBadgeClass generates the Basecoat badge class
func getBadgeClass(variant string) string {
	class := "badge"

	// Add variant suffix if not primary/default
	if variant != "" && variant != "primary" {
		class = "badge-" + variant
	}

	return class
}

// buildTagAttributes creates all HTML attributes for the tag
func buildTagAttributes(props TagProps) templ.Attributes {
	attrs := templ.Attributes{
		"class": getBadgeClass(props.Variant),
	}

	// Core HTML attributes
	if props.ID != "" {
		attrs["id"] = props.ID
	}
	if props.Value != "" {
		attrs["value"] = props.Value
	}

	// Boolean attributes
	if props.Disabled {
		attrs["disabled"] = "disabled"
	}

	// Event handlers
	if props.OnClick != "" {
		attrs["onclick"] = props.OnClick
	}
	if props.OnHover != "" {
		attrs["onmouseover"] = props.OnHover
	}

	// ARIA attributes
	if props.AriaLabel != "" {
		attrs["aria-label"] = props.AriaLabel
	}
	if props.AriaDescribedBy != "" {
		attrs["aria-describedby"] = props.AriaDescribedBy
	}
	if props.AriaPressed != "" {
		attrs["aria-pressed"] = props.AriaPressed
	}
	if props.AriaSelected != "" {
		attrs["aria-selected"] = props.AriaSelected
	}

	// Tab index
	if props.TabIndex != 0 {
		attrs["tabindex"] = strconv.Itoa(props.TabIndex)
	}

	// State data attributes for Basecoat context
	if props.Selected {
		attrs["aria-pressed"] = "true"
	}

	// Data attributes
	for key, value := range props.DataAttrs {
		attrs["data-"+key] = value
	}

	// Merge custom attributes (allows override)
	for key, value := range props.Attributes {
		attrs[key] = value
	}

	return attrs
}

// Tag renders a Basecoat badge atom
func Tag(props TagProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props.Clickable || props.OnClick != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<a")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, buildTagAttributes(props))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " href=\"#\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = renderTagContent(props).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, buildTagAttributes(props))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = renderTagContent(props).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// renderTagContent renders the tag content using Basecoat badge patterns
func renderTagContent(props TagProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props.IconLeft != nil {
			templ_7745c5c3_Err = props.IconLeft.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.Icon != nil && props.Text == "" {
			templ_7745c5c3_Err = props.Icon.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.Text != "" {
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.Text)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/atoms/tags.templ`, Line: 150, Col: 14}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.IconRight != nil {
			templ_7745c5c3_Err = props.IconRight.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.Removable && props.OnRemove != "" {
			templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, props.OnRemove)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<button type=\"button\" class=\"btn-sm-icon-ghost\" onclick=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.ComponentScript = props.OnRemove
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4.Call)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" aria-label=\"Remove tag\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon(IconProps{Name: "x", Size: "sm"}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
