// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package atoms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strconv"

// Note: Basecoat handles label styling via .field wrapper context
// No size or state classes needed - styling is contextual

// LabelProps defines all properties for the Label atom
type LabelProps struct {
	// Core HTML attributes
	For  string `json:"for"`  // Associates with input via id
	Text string `json:"text"` // Label text content

	// Note: Visual styling handled by Basecoat .field context
	// No visual props needed

	// Form semantics
	Required bool `json:"required"` // Shows required indicator
	Disabled bool `json:"disabled"` // Visual disabled state
	Optional bool `json:"optional"` // Shows optional indicator

	// Simple indicator customization
	RequiredText string `json:"requiredText"` // Custom required text (default "*")
	OptionalText string `json:"optionalText"` // Custom optional text (default "(optional)")

	// Event handlers (pre-resolved externally)
	OnClick string `json:"onClick"`

	// ARIA accessibility attributes
	AriaLabel    string `json:"ariaLabel"`
	AriaHidden   string `json:"ariaHidden"`
	AriaRequired string `json:"ariaRequired"`

	// Additional HTML attributes
	TabIndex   int               `json:"tabIndex"`
	DataAttrs  map[string]string `json:"dataAttrs"`
	Attributes templ.Attributes  `json:"attributes"`
}

// Basecoat handles label styling contextually via .field wrapper
// No class generation needed

// buildLabelAttributes creates all HTML attributes for the label
func buildLabelAttributes(props LabelProps) templ.Attributes {
	attrs := templ.Attributes{}

	// Core HTML attributes
	if props.For != "" {
		attrs["for"] = props.For
	}

	// Event handlers
	if props.OnClick != "" {
		attrs["onclick"] = props.OnClick
	}

	// ARIA attributes
	if props.AriaLabel != "" {
		attrs["aria-label"] = props.AriaLabel
	}
	if props.AriaHidden != "" {
		attrs["aria-hidden"] = props.AriaHidden
	}
	if props.AriaRequired != "" {
		attrs["aria-required"] = props.AriaRequired
	}

	// Tab index
	if props.TabIndex != 0 {
		attrs["tabindex"] = strconv.Itoa(props.TabIndex)
	}

	// Data attributes
	for key, value := range props.DataAttrs {
		attrs["data-"+key] = value
	}

	// Merge custom attributes (allows override)
	for key, value := range props.Attributes {
		attrs[key] = value
	}

	return attrs
}

// Label renders a pure presentation label atom
func Label(props LabelProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<label")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, buildLabelAttributes(props))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.Text)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views_backup_20251127_031632/components/atoms/label.templ`, Line: 89, Col: 19}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Required {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.RequiredText != "" {
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.RequiredText)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views_backup_20251127_031632/components/atoms/label.templ`, Line: 95, Col: 39}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "*")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.Optional {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.OptionalText != "" {
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(props.OptionalText)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views_backup_20251127_031632/components/atoms/label.templ`, Line: 106, Col: 39}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "(optional)")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</label>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
